version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: jobboard
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
